   [build]
     publish = "."
     functions = "netlify/functions"

   [dev]
     framework = "#static"
     command = "npm start"
     targetPort = 3001
     port = 8888
     publish = "."

   [[redirects]]
     from = "/api/*"
     to = "/.netlify/functions/:splat"
     status = 200
     force = true